name: Deploy to heroku.

on:
  push:
    branches: [ main ]

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '17.6.0'

    - name: Install Dependencies
      run: npm install
    
    - name: Code Linting
      run: npm run lint
  
  Test:
    runs-on: ubuntu-latest
    needs: Lint
    steps:
    - uses: actions/checkout@v3
    - name: Install NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '17.6.0'

    # - name: Install Dependencies
    #   run: npm install

    # - name: Test and generate coverage report
    #   run: npm run test-cov 
    
    # - name: Upload coverage
    #   run: npm run upload-coverage -- -t ${{ secrets.CODECOV_TOKEN }}

  Deploy:
    runs-on: ubuntu-latest
    needs: [Lint, Test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '17.6.0'

      - name: Install Dependencies
        run: npm install

      - name: Generate docs
        run: npm run swagger-autogen

      - name: Build, Push and Release a Docker image to Heroku. # Your custom step name
        uses: gonuit/heroku-docker-deploy@v1.3.3 
        with:
          # The email address associated with your Heroku account.
          email: "jmejliker@gmail.com"
          
          # Heroku API key associated with provided user's email.
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          
          # Name of the heroku application to which the build is to be sent.
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
